## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [5]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+xpu


## Introduction to Tensors

### Creating tensors

PyTorch tensor are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [7]:
# scalar
scalar = torch.tensor(7).to("xpu")
scalar

tensor(7, device='xpu:0')

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as Python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7]).to("xpu")
vector

tensor([7, 7], device='xpu:0')

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# Matrix

Matrix = torch.tensor([[7, 8], [9, 10]]).to("xpu")
Matrix

tensor([[ 7,  8],
        [ 9, 10]], device='xpu:0')

In [14]:
Matrix.ndim

2

In [16]:
Matrix[1]

tensor([ 9, 10], device='xpu:0')

In [17]:
Matrix.shape

torch.Size([2, 2])

In [19]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]).to("xpu")
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]], device='xpu:0')

In [20]:
Tensor.ndim

3

In [21]:
Tensor.shape

torch.Size([1, 3, 3])

In [22]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]], device='xpu:0')