## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [5]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+xpu


## Introduction to Tensors

### Creating tensors

PyTorch tensor are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [7]:
# scalar
scalar = torch.tensor(7).to("xpu")
scalar

tensor(7, device='xpu:0')

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as Python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7]).to("xpu")
vector

tensor([7, 7], device='xpu:0')

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# Matrix

Matrix = torch.tensor([[7, 8], [9, 10]]).to("xpu")
Matrix

tensor([[ 7,  8],
        [ 9, 10]], device='xpu:0')

In [14]:
Matrix.ndim

2

In [16]:
Matrix[1]

tensor([ 9, 10], device='xpu:0')

In [17]:
Matrix.shape

torch.Size([2, 2])

In [19]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]).to("xpu")
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]], device='xpu:0')

In [20]:
Tensor.ndim

3

In [21]:
Tensor.shape

torch.Size([1, 3, 3])

In [22]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]], device='xpu:0')

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full or random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [29]:
10 * 10 * 10

1000

In [32]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4).to("xpu")
random_tensor

tensor([[0.0450, 0.0608, 0.8704, 0.7094],
        [0.4934, 0.9326, 0.9239, 0.8289],
        [0.8170, 0.8166, 0.6202, 0.6383]], device='xpu:0')

In [40]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)).to("xpu") # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [41]:
random_image_size_tensor

tensor([[[0.9575, 0.8977, 0.9561,  ..., 0.7100, 0.2179, 0.6901],
         [0.3848, 0.6556, 0.6601,  ..., 0.2013, 0.1180, 0.6796],
         [0.9082, 0.1043, 0.0184,  ..., 0.9229, 0.4582, 0.8454],
         ...,
         [0.3526, 0.9225, 0.7978,  ..., 0.1543, 0.5702, 0.3964],
         [0.7273, 0.6396, 0.6804,  ..., 0.8901, 0.4931, 0.3306],
         [0.7678, 0.3886, 0.6258,  ..., 0.0146, 0.9358, 0.4120]],

        [[0.9745, 0.5301, 0.8212,  ..., 0.0379, 0.4767, 0.7049],
         [0.1074, 0.9279, 0.0740,  ..., 0.3140, 0.0131, 0.1799],
         [0.2765, 0.3072, 0.8661,  ..., 0.2060, 0.4662, 0.8441],
         ...,
         [0.9026, 0.4798, 0.6178,  ..., 0.6940, 0.9983, 0.0069],
         [0.7605, 0.1951, 0.8737,  ..., 0.9175, 0.7468, 0.3868],
         [0.7951, 0.8032, 0.7067,  ..., 0.5896, 0.8632, 0.3059]],

        [[0.2412, 0.7695, 0.9208,  ..., 0.8243, 0.8928, 0.7241],
         [0.9387, 0.2094, 0.7110,  ..., 0.3050, 0.0757, 0.8066],
         [0.4648, 0.9102, 0.3461,  ..., 0.8395, 0.7545, 0.